export const REFACTORING_HOME_URL = 'https://refactoring.fm/'
export const TOLARIA_DOCS_URL = 'https://memnova.net/'
export const TOLARIA_PRODUCT_BOARD_URL = 'https://memnova.net/'
export const TOLARIA_GITHUB_DISCUSSIONS_URL = 'https://github.com/phongthanhbuiit/tolaria-memnova/discussions'
export const TOLARIA_GITHUB_CONTRIBUTING_URL = 'https://github.com/phongthanhbuiit/tolaria-memnova/blob/main/CONTRIBUTING.md'
export const TOLARIA_GITHUB_ISSUES_URL = 'https://github.com/phongthanhbuiit/tolaria-memnova/issues'
export const TOLARIA_GITHUB_PULL_REQUESTS_URL = 'https://github.com/phongthanhbuiit/tolaria-memnova/pulls'
